
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'paradime'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'paradime'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  # start of re_data related config
  re_data:save_test_history: true
  # querying BigQuery for failing rows
  re_data:query_test_failures: false
  
  
  # limit the number of failed rows returned per test
  re_data:test_history_failures_limit: 10
  re_data:metrics_groups:
    table_metrics:
      table:
        - row_count
        - freshness

    column_metrics:
      column:
        numeric:
          - nulls_count
          - nulls_percent

        text:
          - missing_count
          - missing_percent
          - nulls_count
          - nulls_percent

  re_data:default_metrics:
    - table_metrics
    - column_metrics  

models:
  paradime:
    materialized: view
    stage:
      schema: stage

    analys:
      +re_data_monitored: true
      materialized: table
      schema: analys

    mart:
      +re_data_monitored: true
      materialized: table
      schema: mart
    re_data:
        +schema: re
        internal:
          +schema: re_internal
