version: 2

sources:
  - name: stage
    schema: raw
    tables:
      - name: citibike_trips
        description: Stage Citibike Trips
        columns:
          - name: tripduration
            description: "Trip Duration (in seconds)"

          - name: starttime
            description: "Start Time, in NYC local time."

          - name: stoptime
            description: "Stop Time, in NYC local time."

          - name: start_station_id
            description: "Start Station ID"

          - name: start_station_name
            description: "Start Station Name"

          - name: start_station_latitude
            description: "Start Station Latitude"

          - name: start_station_longitude
            description: "Start Station Longitude"

          - name: end_station_id
            description: "End Station ID"

          - name: end_station_name
            description: "End Station Name"

          - name: end_station_latitude
            description: "End Station Latitude"

          - name: end_station_longitude
            description: "End Station Longitude"

          - name: bikeid
            description: "Bike ID"

          - name: usertype
            description: "User Type (Customer = 24-hour pass or 7-day pass user, Subscriber = Annual Member)"

          - name: birth_year
            description: "Year of Birth"

          - name: gender
            description: "Gender (unknown, male, female)"

      # - name: citibike_stations